# Site
name: 'Blog'
description: 'Welcome to my personal blog!'
logo: 'assets/avatars/tuan.png'
favicon: 'assets/avatars/tuan.png'
baseurl: ''
disqus: 'tuanb-me'
email: 'ntuanb@gmail.com'
mailchimp-list: 'https://whiskyd.us16.list-manage.com/subscribe/post?u=1c791dbb1bcdb3f0dcaf380ae&amp;id=61fed065e3'

include: ["_pages"]
permalink: /:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  
authors:
    tuan:
      name:           Tuan
      site:           https://blog.tuanb.me
      avatar:         /assets/images/avatars/tuan.png
      bio:            "I love javascript, automation and write code for no reason."
      email:          ntuanb@gmail.com
      twitter:        
 
# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: tuan
      avatar: /assets/avatars/tuan.png
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10



# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]