title: Blog
baseurl: "https://blog.tuanb.me"
email: ntuanb@gmail.com
url: "https://blog.tuanb.me"
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-paginate

highlighter: rouge
markdown: kramdown

# Tracker
analytics: "UA-90397102-1"

# Comments
disqus-shortname: tuanb-me

compress_html:
  clippings: [html,div, p, ul, td, h1, h2, h3, h4,link, meta, footer, nav, img, header, hr, br, head, style, li, ul, ol, time, main, script, title]
  comments: ["<!-- ", " -->"]
  endings: [all]
  ignore:
    envs: [local]
  blanklines: false
  profile: false
  startings: []

sass:
 style: compressed

exclude:
- README.md
