# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Tuan B
tagline:          'Developer'
description:      'Developer'
url:              http://ntuanb.com/
baseurl:          /

author:
  name:           'Tuan B'
  url:            http://ntuanb.com/

paginate:         5

# Custom vars
version:          1.0.0

github:
  repo:
